#!/bin/bash
#
# Publish new gem version and creates GH tag for it.
#
###
#git diff --quiet HEAD~ VERSION
#if [ `git diff --quiet HEAD~ VERSION` -ne 0 ]; then
#  echo "11111111"
#else
#  echo "22222222"
#fi

#VERSION_BUMPED=`git diff --quiet HEAD~ VERSION`
if [[ "`git diff --quiet HEAD~ VERSION`" -ne 0 ]]
then
  echo "11111111"
else
  echo "22222222"
fi
