version: 2
jobs:
  build_test:
    environment:
      CC_TEST_REPORTER_ID: e70e48da820d9d23eeb2f1fd8c25f8691be05af308dd0ffce8d1ca7e48a5f799
    machine: true
    steps:
      - checkout
      - run:
          name: Install test reporter
          command: |
            curl -L -o "cc-test-reporter" "https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64"
            sudo chmod +x ./cc-test-reporter
      - run: make image
      - run: make citest

  publish:
    environment:
      CC_TEST_REPORTER_ID: e70e48da820d9d23eeb2f1fd8c25f8691be05af308dd0ffce8d1ca7e48a5f799
    machine: true
    #  image: ubuntu-2004:202010-01

    steps:
      - checkout
      - run: |
          sudo apt update && sudo apt install -y git wget
          url="$(wget -qO- https://api.github.com/repos/github/hub/releases/latest | tr '"' '\n' | grep '.*/download/.*/hub-linux-amd64-.*.tgz')"
          wget -qO- "$url" | sudo tar -xzvf- -C /usr/bin --strip-components=2 --wildcards "*/bin/hub"
      #- run: sudo add-apt-repository ppa:cpick/hub && sudo apt-get update && sudo apt-get install hub
      - run:
          command: |
            if [ `git diff --quiet HEAD~ VERSION; echo $?` == 1 ]; then
              ./bin/publish
            fi

workflows:
  version: 2
  #build_test:
  #  jobs:
  #    - build_test
  #    - publish:
  #        requires:
  build_test:
    jobs:
      - publish

#notify:
#  webhooks:
#    - url: https://cc-slack-proxy.herokuapp.com/circle
